fit(RHTAPBUGS-756): set digest in repo when creating an image in Pyxis
redhat-appstudio/release-service-utils pull request #58
Opened 2023-09-12 08:22 UTC by mmalina

Based on the mediaType returned by `skopeo inspect --raw`, the create_container_image will determine if the image is single arch or multi arch and based on that
it will populate either manifest_schema2_digest
or manifest_list_digest in the embedded
ContainerImageRepo object when creating a new
image in Pyxis.

This also removes the docker_image_digest and
image_id fields when creating the image. This is to align with metaxor which does not populate these either.

Note that currently we do not really support multi arch images in RHTAP and other changes will likely be needed to fully support them.

2023-09-12 08:22 UTC, mmalina commented
@ralphbean PTAL

2023-09-12 09:29 UTC, kasemAlem commented on pyxis/test_create_container_image.py
> +    args.media_type = "application/vnd.docker.distribution.manifest.v2+json"
what is the point of doing this assignment here while you already ran it in line 61?

2023-09-12 11:36 UTC, mmalina commented on pyxis/test_create_container_image.py
> +    args.media_type = "application/vnd.docker.distribution.manifest.v2+json"
Line 61 is a different test. This one is `test_create_container_image_latest` and the other one is `test_create_container_image`. They are fairly similar, the main difference is that this one is testing the scenario with "latest" tag.

2023-09-12 11:43 UTC, kasemAlem commented on pyxis/test_create_container_image.py
> +    args.media_type = "application/vnd.docker.distribution.manifest.v2+json"
I see, 
thanks

2023-09-12 12:15 UTC, johnbieren commented on pyxis/create_container_image.py
> +        "--media-type",
we already pass the entire `skopeo inspect` output. We can't just extract it from the file instead of having to pass another argument?

2023-09-12 12:24 UTC, johnbieren commented on pyxis/create_container_image.py
> +        "--media-type",
I see. It sucks we need to skopeo inspect twice and neither way of calling it gives us all we need. But it looks like you and others already investigated that on the JIRA

2023-09-12 12:24 UTC, johnbieren approved these changes

2023-09-12 12:24 UTC, johnbieren requested changes
The commit message prefix is wrong. Guess we don't have CI for that in this repo

2023-09-12 12:33 UTC, mmalina commented
> The commit message prefix is wrong. Guess we don't have CI for that in this repo

Good catch. I fixed the commit message. But you're right the linting workflow doesn't work - in fact the workflow file is missing. It was supposed to be enabled here: https://github.com/redhat-appstudio/release-service-utils/pull/55 I will create a bug.

2023-09-12 12:37 UTC, johnbieren approved these changes

2023-09-12 13:30 UTC, scoheb submitted a review, later dismissed

2023-09-12 14:22 UTC, kasemAlem approved these changes

2023-09-12 14:46 UTC, davidmogar commented on pyxis/create_container_image.py
> +        help="The mediaType string returned by `skopeo inspect --raw`. "
```suggestion
        help="The mediaType string returned by `skopeo inspect --raw`."
```

2023-09-12 14:46 UTC, davidmogar commented on pyxis/create_container_image.py
> +        container_image_payload["repositories"][0][
Cleaner as a one-liner.

2023-09-12 14:46 UTC, davidmogar commented on pyxis/create_container_image.py
> +        container_image_payload["repositories"][0][
Cleaner as a one-liner. Not that long isn't it?

2023-09-12 14:46 UTC, davidmogar commented on pyxis/test_create_container_image.py
> +    # single arch image,
I don't get this comment and it has an extra comma.

2023-09-12 14:46 UTC, davidmogar commented on pyxis/test_create_container_image.py
> +    # single arch image
I don't get this comment.

2023-09-13 08:34 UTC, mmalina commented on pyxis/create_container_image.py
> +        help="The mediaType string returned by `skopeo inspect --raw`. "
@davidmogar I disagree. The string continues on the next line. So the result will be those two strings joined. I want a space between the two sentences.

2023-09-13 08:34 UTC, mmalina commented on pyxis/create_container_image.py
> +        container_image_payload["repositories"][0][
This was done by Black formatter, because the line was too long.

2023-09-13 08:35 UTC, mmalina commented on pyxis/create_container_image.py
> +        container_image_payload["repositories"][0][
I think it is. I didn't do this myself, the Black formatter did it.

2023-09-13 08:40 UTC, mmalina commented on pyxis/test_create_container_image.py
> +    # single arch image,
Removed the extra comma, thanks.

The mediaType value should/will be one of these:
```
application/vnd.oci.image.manifest.v1+json
application/vnd.docker.distribution.manifest.v1+json
application/vnd.docker.distribution.manifest.v2+json
application/vnd.oci.image.index.v1+json
application/vnd.docker.distribution.manifest.list.v2+json
```

The first three imply it's a single arch image, the last two imply it's a multi arch image. Based on this value we will populate one of the two fields.

Since we're really only deciding between the two possibilities, I decided that we just need to define the "manifest list" / "oci index" strings and otherwise assume it's a manifest. Should I maybe add the other strings as a comment near where I define `MANIFEST_LIST_TYPES` in the create_container_image script? Or what else would you suggest?

2023-09-13 14:08 UTC, ralphbean submitted a review, later dismissed

2023-09-14 08:44 UTC, mmalina commented
@davidmogar @johnbieren can you check again please? I had to refactor this a bit - I realized that the original `image_already_exists()` function won't work either since it was relying on the `docker_image_digest` field which we will no longer populate. Now it will check the right field in the embedded repository object. (The commit message is updated to include this.)

2023-09-14 10:39 UTC, davidmogar approved these changes

2023-09-14 12:29 UTC, johnbieren approved these changes

2023-09-14 12:29 UTC, johnbieren commented on pyxis/create_container_image.py
> +    # return False
I am confused by this comment

2023-09-14 12:58 UTC, mmalina commented on pyxis/create_container_image.py
> +    # return False
Busted! I needed to skip the test for testing ;)

2023-09-14 13:04 UTC, johnbieren approved these changes

2023-09-14 13:09 UTC, merged