chore(HACBS-2593): internal-request script should fail on IR failure
redhat-appstudio/release-service-utils pull request #59
Opened 2023-09-19 12:42 UTC by theflockers

This PR fixes the script to make it check if the InternalRequest
has Succeeded or not and exit accordingly.

Signed-off-by: Leandro Mendes <lmendes@redhat.com>

2023-09-19 13:02 UTC, johnbieren submitted a review, later dismissed

2023-09-19 14:21 UTC, theflockers commented on utils/internal-request
> +          [ "${CONDITION_REASON}" == "Succeeded" ]; exit $?
Cool. I changed but added more output only for the failed case.

2023-09-20 08:10 UTC, davidmogar commented
That was actually on purpose as you can see in the script header:
```
# This script creates an InternalRequest resource in a Kubernetes cluster
# using the 'kubectl' command line tool. The resource is created with
# parameters passed to the script, and optionally waits for the resource to
# reach a 'completed' status.
```

I delegated the check for the caller as a succeeded or failed condition would probably still require the resource to be loaded to check the results or the condition message respectively.

I'm not saying I oppose to the change. Just saying that it wasn't the goal.

In addition, the Rejected status is not taken into account in this PR. Failed and Rejected are grouped together, which again would require to load the resource to see what happened.

2023-09-20 09:06 UTC, mmalina commented on utils/internal-request
> +            echo $CONDITIONS
Nit: I would suggest: 
```sh
echo Conditions: 
echo $CONDITIONS
```

2023-09-20 09:08 UTC, mmalina commented on utils/internal-request
>        CONDITIONS=$(kubectl get internalrequest "$INTERNAL_REQUEST_NAME" -o json | jq -r '.status.conditions')
The `-r` in `jq -r` is redundant here. The result is a json array. `--raw` only has effect if the result is a string:

> With this option, if the filter's result is a string then it will be written directly to standard output rather than being formatted as a JSON string with quotes.

2023-09-20 09:08 UTC, mmalina commented on utils/internal-request
> +          [ "${CONDITION_REASON}" == "Succeeded" ]; exit $?
Nice, thanks. Added a few more small comments.

2023-09-20 09:15 UTC, mmalina commented
> That was actually on purpose

I was actually wondering if this was the case. And it's a valid argument - depending on what the internal request was, the caller might want to do different things to check why it failed. But on the other hand the calling script can _catch_ this failure and still check what actually happened on its own. So I'm fine either way. But in both cases, this should be clearly documented in the script description (currently it's not clear what happens).

2023-09-20 10:00 UTC, theflockers commented
> That was actually on purpose as you can see in the script header:
> 
> ```
> # This script creates an InternalRequest resource in a Kubernetes cluster
> # using the 'kubectl' command line tool. The resource is created with
> # parameters passed to the script, and optionally waits for the resource to
> # reach a 'completed' status.
> ```
> 
> I delegated the check for the caller as a succeeded or failed condition would probably still require the resource to be loaded to check the results or the condition message respectively.
> 
> I'm not saying I oppose to the change. Just saying that it wasn't the goal.
> 
> In addition, the Rejected status is not taken into account in this PR. Failed and Rejected are grouped together, which again would require to load the resource to see what happened.

I understand but I can't see a reason (so far) where the IR would fail and we should still continue.  
I see this like any other script or command that return non zero in case of non-success (like `grep` for instance). 

Knowing that the IR did not succeeded by the exit code IMHO should be default behavior as we can still test the exit code of the script to avoid premature exit.

2023-09-20 11:09 UTC, davidmogar commented
> > That was actually on purpose as you can see in the script header:
> > ```
> > # This script creates an InternalRequest resource in a Kubernetes cluster
> > # using the 'kubectl' command line tool. The resource is created with
> > # parameters passed to the script, and optionally waits for the resource to
> > # reach a 'completed' status.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I delegated the check for the caller as a succeeded or failed condition would probably still require the resource to be loaded to check the results or the condition message respectively.
> > I'm not saying I oppose to the change. Just saying that it wasn't the goal.
> > In addition, the Rejected status is not taken into account in this PR. Failed and Rejected are grouped together, which again would require to load the resource to see what happened.
> 
> I understand but I can't see a reason (so far) where the IR would fail and we should still continue. I see this like any other script or command that return non zero in case of non-success (like `grep` for instance).
> 
> Knowing that the IR did not succeeded by the exit code IMHO should be default behavior as we can still test the exit code of the script to avoid premature exit.

Yes, as stated, the script was not created that way. It was meant to create IR and, optionally, wait for them to finish (independently of the result). In this context, the script should exclusively error in the case of a problem creating the resource. With the changes, the script could fail this way or could fail because the IR failed. If you want to go that way, do it. But if we go that way, proper documentation and proper error codes should be put into place. If not we just simply let the called to check the outcome of the request as it would still have to load it in any case.

Regarding an example for an IR failing and still continue, let's say that we need to call a service as soon as we did something and not wait for another PipelineRun to be re-run to fix the error. I don't know. I agree with this being not needed today, but I don't see it either as a problem.

In any case, leaving the decision to the team ;)

2023-09-20 11:48 UTC, theflockers commented
Any other opinions @johnbieren @happybhati @scoheb?

2023-09-20 12:10 UTC, scoheb commented
> Any other opinions @johnbieren @happybhati @scoheb?

My only requirement or opinion is that as a user, something that fails in a script but shows as passed is not good. Either the script should fail or the calling task/pipeline should fail.

2023-09-20 14:05 UTC, theflockers commented
Also, the default behavior of the script is watch the internal request. So, if we are waiting it to finish, it makes sense IMHO that you want to know the result of it.

In the other hand, for an _async_ call (`-s false`) it exists exits with 0 and you need to watch the IR in the task itself.

2023-09-21 13:13 UTC, theflockers commented
@johnbieren could you give your thoughts here? See David's comment, please.

2023-09-21 13:16 UTC, johnbieren commented
> @johnbieren could you give your thoughts here? See David's comment, please.

I really do not know enough about this script to decide its behavior

2023-09-21 13:25 UTC, happybhati commented
> > Any other opinions @johnbieren @happybhati @scoheb?
> 
> My only requirement or opinion is that as a user, something that fails in a script but shows as passed is not good. Either the script should fail or the calling task/pipeline should fail.

I would +1 what Scott said; either way, this should be documented in the script description(as Martin suggested).

2023-09-21 13:49 UTC, theflockers commented
Ok. I will then adjust the doc a bit and move forward with the change.

2023-09-25 10:10 UTC, davidmogar requested changes

2023-09-25 10:10 UTC, davidmogar commented on utils/internal-request
> +# In sync mode (default) it waits for the InternalRequest to reach a 'completed'
```suggestion
# In sync mode (default) the script waits for the InternalRequest to reach a 'completed'
```

2023-09-25 11:30 UTC, davidmogar commented on utils/internal-request
> +            exit $EXIT_CODE
Is this tested? Does it work? Unsure about variable scope in bash.

2023-09-25 12:23 UTC, theflockers commented on utils/internal-request
> +            exit $EXIT_CODE
Yes, it does. Tested of all 3 scenarios.

2023-09-25 12:30 UTC, theflockers commented on utils/internal-request
> +            exit $EXIT_CODE
# case Success
```
+ CONDITION_REASON=Succeeded
+ '[' Succeeded == Running ']'
+ case $CONDITION_REASON in
InternalRequest succeeded
+ echo 'InternalRequest succeeded'
+ EXIT_CODE=0
+ echo Conditions:
Conditions:
[ { "lastTransitionTime": "2023-09-25T12:29:31Z", "message": "", "reason": "Succeeded", "status": "True", "type": "Succeeded" } ]
+ echo '[' '{' '"lastTransitionTime":' '"2023-09-25T12:29:31Z",' '"message":' '"",' '"reason":' '"Succeeded",' '"status":' '"True",' '"type":' '"Succeeded"' '}' ']'
+ exit 0
```

# case Failed
```
+ CONDITION_REASON=Failed
+ '[' Failed == Running ']'
+ case $CONDITION_REASON in
InternalRequest failed
+ echo 'InternalRequest failed'
+ EXIT_CODE=21
Conditions:
+ echo Conditions:
+ echo '[' '{' '"lastTransitionTime":' '"2023-09-25T11:07:06Z",' '"message":' '"Tasks' Completed: 1 '(Failed:' 1, Cancelled '0),' Skipped: '0",' '"reason":' '"Failed",' '"status":' '"False",' '"type":' '"Succeeded"' '}' ']'
[ { "lastTransitionTime": "2023-09-25T11:07:06Z", "message": "Tasks Completed: 1 (Failed: 1, Cancelled 0), Skipped: 0", "reason": "Failed", "status": "False", "type": "Succeeded" } ]
+ exit 21
```

# case Rejected
```
v+ CONDITION_REASON=Rejected
+ '[' Rejected == Running ']'
+ case $CONDITION_REASON in
+ echo 'InternalRequest rejected'
+ EXIT_CODE=22
+ echo Conditions:
+ echo '[' '{' '"lastTransitionTime":' '"2023-09-25T11:09:57Z",' '"message":' '"the' internal request namespace '(managed-release-team-tenant)' is not in the allow 'list",' '"reason":' '"Rejected",' '"status":' '"False",' '"type":' '"Succeeded"' '}' ']'
+ exit 22
```

2023-09-25 12:37 UTC, davidmogar commented
These PR changes the behavior of, at least, a release service bundle task. Do we need a change in there?

2023-09-25 13:06 UTC, theflockers commented
It is not required. With the change it will now behave as expected. - Fail on error.

2023-09-26 07:46 UTC, davidmogar approved these changes

2023-09-26 09:59 UTC, merged