chore(RHTAPREL-435): pin base image and update labels
redhat-appstudio/release-service-utils pull request #66
Opened 2023-10-11 13:12 UTC by scoheb

- pin base image in Dockerfile
- specify labels that we should not be overriding

2023-10-11 13:21 UTC, johnbieren approved these changes

2023-10-11 16:58 UTC, johnbieren commented on Dockerfile
> -RUN curl -L https://github.com/stedolan/jq/releases/download/jq-{JQ_VERSION}/jq-linux64 -o /usr/bin/jq &&\
Why the changes to the `RUN`?

2023-10-11 18:24 UTC, scoheb commented on Dockerfile
> -RUN curl -L https://github.com/stedolan/jq/releases/download/jq-{JQ_VERSION}/jq-linux64 -o /usr/bin/jq &&\
This is a test to determine which binary is causing an image layer to have high vulnerability.

2023-10-12 17:21 UTC, johnbieren requested changes
We use jq extensively in our tasks. We can't remove it from the image

2023-10-12 18:45 UTC, scoheb commented
> We use jq extensively in our tasks. We can't remove it from the image

We install it immediately after via `dnf`:

https://github.com/redhat-appstudio/release-service-utils/blob/6caa5f1c252f17276465b4d2dcf2242b66356bea/Dockerfile#L18

2023-10-12 18:53 UTC, johnbieren commented
> > We use jq extensively in our tasks. We can't remove it from the image
> 
> We install it immediately after via `dnf`:
> 
> https://github.com/redhat-appstudio/release-service-utils/blob/6caa5f1c252f17276465b4d2dcf2242b66356bea/Dockerfile#L18

Oh wow. I was the one who approved that addition installing it via curl when we already dnf installed it too. Oops. Hopefully no version diff issues once we merge this...

2023-10-12 18:53 UTC, johnbieren approved these changes

2023-10-12 19:23 UTC, scoheb commented
> > > We use jq extensively in our tasks. We can't remove it from the image
> > 
> > 
> > We install it immediately after via `dnf`:
> > https://github.com/redhat-appstudio/release-service-utils/blob/6caa5f1c252f17276465b4d2dcf2242b66356bea/Dockerfile#L18
> 
> Oh wow. I was the one who approved that addition installing it via curl when we already dnf installed it too. Oops. Hopefully no version diff issues once we merge this...

I can put it back to reduce the risk...but it seems safer to get it from `dnf`

2023-10-12 19:27 UTC, johnbieren commented
> > > > We use jq extensively in our tasks. We can't remove it from the image
> > > 
> > > 
> > > We install it immediately after via `dnf`:
> > > https://github.com/redhat-appstudio/release-service-utils/blob/6caa5f1c252f17276465b4d2dcf2242b66356bea/Dockerfile#L18
> > 
> > 
> > Oh wow. I was the one who approved that addition installing it via curl when we already dnf installed it too. Oops. Hopefully no version diff issues once we merge this...
> 
> I can put it back to reduce the risk...but it seems safer to get it from `dnf`

Yeah I say get it only from dnf and if we have issues we can deal with them

2023-10-12 19:30 UTC, merged