feat(RHTAPREL-618): add rh-push option when creating pyxis image
redhat-appstudio/release-service-utils pull request #76
Opened 2023-10-27 06:49 UTC by mmalina

If set to true, the registry and repository entries in the Pyxis Container Image object will be converted to use Red Hat's official registry. E.g. a mapped repository
of quay.io/redhat-pending/product---my-image will be converted to use registry registry.access.redhat.com and repository product/my-image.

Also, the image will be marked as published.

This will be used in the rh-push-to-registry-redhat-io pipeline.

2023-10-27 11:27 UTC, scoheb requested changes

2023-10-27 11:27 UTC, scoheb commented on pyxis/create_container_image.py
> +        help="If set to true, the registry and repository entries in the Pyxis Container "
Missing a word?

2023-10-27 11:27 UTC, scoheb commented on pyxis/create_container_image.py
> +        "registry registry.access.redhat.com and repository product/my-image. Also, "
I am always confused by this. When do you specify `access` and when do you specify ` registry.redhat.io`?

2023-10-27 12:36 UTC, mmalina commented on pyxis/create_container_image.py
> +        help="If set to true, the registry and repository entries in the Pyxis Container "
No, the string is split into multiple lines to avoid a line too long. See the next lines.

2023-10-27 12:41 UTC, mmalina commented on pyxis/create_container_image.py
> +        "registry registry.access.redhat.com and repository product/my-image. Also, "
AFAIK, it's always `registry.access.redhat.com`. `registry.access.redhat.com` was here first. Then `registry.redhat.io` came along. Which one is used is controlled by the `requires_terms` flag in [the Container Repository object](https://pyxis.engineering.redhat.com/docs/objects/ContainerRepository.html?tab=Fields). (It is/was also possible to use both, but I'm not sure how that is achieved.) Nowadays everybody should use `requires_terms=true` by default. To use the public repo, you would need an exception. So I assume in RHTAP we currently only plan to use the authenticated one (registry.redhat.io).

2023-10-27 13:19 UTC, scoheb commented on pyxis/create_container_image.py
> +        help="If set to true, the registry and repository entries in the Pyxis Container "
yep. sorry

2023-10-27 13:34 UTC, scoheb commented on pyxis/create_container_image.py
> +        "registry registry.access.redhat.com and repository product/my-image. Also, "
can we summarise this and add to help? or as a comment? I think this is golden info

2023-10-30 09:01 UTC, mmalina commented on pyxis/create_container_image.py
> +        "registry registry.access.redhat.com and repository product/my-image. Also, "
I added a lengthy note about this in the script description (at the top). Please check.

2023-10-30 12:38 UTC, scoheb approved these changes

2023-10-30 12:38 UTC, scoheb commented on pyxis/create_container_image.py
> +        "registry registry.access.redhat.com and repository product/my-image. Also, "
thanks!

2023-10-30 12:50 UTC, johnbieren approved these changes

2023-10-30 12:54 UTC, merged